/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bsptechs.main.bean.ui.frame;

import com.bsptechs.main.Config;
import com.bsptechs.main.Main;
import com.bsptechs.main.bean.SUArrayList;
import com.bsptechs.main.bean.server.SUQueryBean;
import com.bsptechs.main.bean.server.SUConnectionBean;
import com.bsptechs.main.bean.server.SUDatabaseBean;
import com.bsptechs.main.dao.impl.DatabaseDAOImpl;
import java.util.List;

/**
 *
 * @author Goshgar
 */
public class SetQueryLocation extends javax.swing.JFrame {

    /**
     * Creates new form SetQueryLocation
     */
    DatabaseDAOImpl dao = new DatabaseDAOImpl();
    private String queryBody;
    private final SUDatabaseBean selectedDatabase = Main.instance().getConnectionTree().getCurrentDatabaseNode().getDatabase();
    private final SUConnectionBean selectedConnection = Main.instance().getConnectionTree().getCurrentConnectionNode().getConnection();

    public void setQueryBody(String queryBody) {
        this.queryBody = queryBody;
    }

    public SetQueryLocation() {
        initComponents();
        frameFirstOpened();
        fillConnectionCombo();
        fillDatabaseCmbo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUserAgre = new javax.swing.JPanel();
        txtQueryName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblQueryLocation = new javax.swing.JLabel();
        userChoice = new javax.swing.JToggleButton();
        pnlUserChoice = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbDatabase = new javax.swing.JComboBox<>();
        cmbConnection = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtQueryName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));

        jLabel1.setText("Enter query name:");

        jLabel2.setText("Save Location:");

        lblQueryLocation.setText("localhost");

        userChoice.setText(">");
        userChoice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserAgreLayout = new javax.swing.GroupLayout(pnlUserAgre);
        pnlUserAgre.setLayout(pnlUserAgreLayout);
        pnlUserAgreLayout.setHorizontalGroup(
            pnlUserAgreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserAgreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserAgreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQueryName)
                    .addGroup(pnlUserAgreLayout.createSequentialGroup()
                        .addGroup(pnlUserAgreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlUserAgreLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(121, 121, 121))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserAgreLayout.createSequentialGroup()
                                .addComponent(lblQueryLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(userChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addContainerGap())))
        );
        pnlUserAgreLayout.setVerticalGroup(
            pnlUserAgreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserAgreLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQueryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pnlUserAgreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQueryLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userChoice))
                .addGap(7, 7, 7))
        );

        jLabel3.setText("Connection:");

        jLabel4.setText("Schema:");

        cmbDatabase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDatabaseItemStateChanged(evt);
            }
        });

        cmbConnection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbConnectionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlUserChoiceLayout = new javax.swing.GroupLayout(pnlUserChoice);
        pnlUserChoice.setLayout(pnlUserChoiceLayout);
        pnlUserChoiceLayout.setHorizontalGroup(
            pnlUserChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDatabase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUserChoiceLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbConnection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlUserChoiceLayout.setVerticalGroup(
            pnlUserChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserChoiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSubmit.setText("OK");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUserAgre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlUserChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUserAgre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUserChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int pnlUserChoiceHeight;

    private void frameFirstOpened() {
        pnlUserChoiceHeight = pnlUserChoice.getHeight();
        int thisSizeWithoutUserChooice = this.getHeight() - pnlUserChoice.getHeight();
        this.setSize(this.getWidth(), thisSizeWithoutUserChooice);
        pnlUserChoice.setVisible(false);
    }

    private List<SUConnectionBean> fillConnectionCombo() {
        Config.initialize();
        List<SUConnectionBean> connections = Config.getConnectionBeans();
        connections.forEach((connection) -> {
            cmbConnection.addItem(connection);
        });
        cmbConnection.setSelectedItem(selectedConnection);
        return connections;
    }

    private void fillDatabaseCmbo() {
        cmbDatabase.removeAllItems();
        SUDatabaseBean firstDatabase = null;
        cmbDatabase.addItem(firstDatabase);
        SUConnectionBean selectedConnection = (SUConnectionBean) cmbConnection.getSelectedItem();
        SUArrayList<SUDatabaseBean> databases = dao.getAllDatabases(selectedConnection);
        databases.forEach((database) -> {
            cmbDatabase.addItem(database);
        });
        cmbDatabase.setSelectedItem(selectedDatabase);
    }

    private void saveQuery() {
        String queryName = txtQueryName.getText();
        SUConnectionBean selectedConnection = (SUConnectionBean) cmbConnection.getSelectedItem();
        SUDatabaseBean selectedDatabase = (SUDatabaseBean) cmbDatabase.getSelectedItem();
        SUQueryBean savedQuery = new SUQueryBean(selectedConnection, selectedDatabase, queryBody, queryName);
        dao.saveQuery(selectedConnection, savedQuery);
        Config.initialize();
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        saveQuery();
        this.dispose();

    }//GEN-LAST:event_btnSubmitActionPerformed
    int key = 0;
    private void userChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userChoiceActionPerformed
        key++;
        if (key % 2 == 1) {
            this.setSize(this.getWidth(), this.getHeight() + pnlUserChoiceHeight);
            btnCancel.setVisible(false);
            btnSubmit.setVisible(false);
            pnlUserChoice.setVisible(true);
            btnCancel.setVisible(true);
            btnSubmit.setVisible(true);
        }
        if (key % 2 == 0) {
            this.setSize(this.getWidth(), this.getHeight() - pnlUserChoiceHeight);
            btnCancel.setVisible(true);
            btnSubmit.setVisible(true);
            pnlUserChoice.setVisible(false);
            btnCancel.setVisible(true);
            btnSubmit.setVisible(true);

        }

    }//GEN-LAST:event_userChoiceActionPerformed

    private void cmbConnectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbConnectionItemStateChanged
        if (cmbDatabase.getSelectedItem() != null) {
            lblQueryLocation.setText(cmbConnection.getSelectedItem().toString() + "/" + cmbDatabase.getSelectedItem().toString());
        }
        lblQueryLocation.setText(cmbConnection.getSelectedItem().toString());
    }//GEN-LAST:event_cmbConnectionItemStateChanged

    private void cmbDatabaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDatabaseItemStateChanged
        if (cmbDatabase.getSelectedItem() == null) {
            lblQueryLocation.setText(cmbConnection.getSelectedItem().toString());
        } else {
            lblQueryLocation.setText(cmbConnection.getSelectedItem().toString() + "/" + cmbDatabase.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbDatabaseItemStateChanged
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetQueryLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetQueryLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetQueryLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetQueryLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetQueryLocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<SUConnectionBean> cmbConnection;
    private javax.swing.JComboBox<SUDatabaseBean> cmbDatabase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblQueryLocation;
    private javax.swing.JPanel pnlUserAgre;
    private javax.swing.JPanel pnlUserChoice;
    private javax.swing.JTextField txtQueryName;
    private javax.swing.JToggleButton userChoice;
    // End of variables declaration//GEN-END:variables
}
