/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bsptechs.main.bean.table.dataTypePanel;

/**
 *
 * @author Goshgar
 */
public class WoutAIPanel extends DataTypePanel {

    /**
     * Creates new form WoutAIPanel
     */
    public WoutAIPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unsigned = new javax.swing.JCheckBox();
        zerofill = new javax.swing.JCheckBox();

        unsigned.setText("Unsigned");
        unsigned.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unsignedItemStateChanged(evt);
            }
        });
        unsigned.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                unsignedStateChanged(evt);
            }
        });

        zerofill.setText("Zerofill");
        zerofill.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                zerofillItemStateChanged(evt);
            }
        });
        zerofill.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zerofillStateChanged(evt);
            }
        });
        zerofill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerofillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unsigned, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(zerofill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(unsigned)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zerofill)
                .addGap(0, 28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void unsignedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unsignedItemStateChanged
    
    }//GEN-LAST:event_unsignedItemStateChanged

    private void unsignedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_unsignedStateChanged

    }//GEN-LAST:event_unsignedStateChanged

    private void zerofillItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_zerofillItemStateChanged
       
    }//GEN-LAST:event_zerofillItemStateChanged

    private void zerofillStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zerofillStateChanged

    }//GEN-LAST:event_zerofillStateChanged

    private void zerofillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerofillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zerofillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox unsigned;
    private javax.swing.JCheckBox zerofill;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getQuery() {
       return null;
    }
}
