/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bsptechs.main.bean.ui.panel.queryresult;

import com.bsptechs.main.bean.server.SUQueryBean;
import com.bsptechs.main.bean.server.SUQueryResult;
import com.bsptechs.main.bean.ui.table.SUTable;
import com.bsptechs.main.bean.ui.table.SUTableRow;
import com.bsptechs.main.dao.impl.DatabaseDAOImpl;
import com.bsptechs.main.dao.inter.DatabaseDAOInter;
import java.awt.event.KeyEvent;
import lombok.SneakyThrows;
import com.bsptechs.main.util.LogUtil;
/**
 *
 * @author sarkhanrasullu
 */
public class PanelQueryResult extends javax.swing.JPanel {

    private static final DatabaseDAOInter db = new DatabaseDAOImpl();

    /**
     * Creates new form PanelQueryResult
     */
    public PanelQueryResult() {
        initComponents();
        setTableMode(SU_TABLE_MODE.ADD_DISABLE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnSaveChangesForTable = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblQueryResult = new com.bsptechs.main.bean.ui.table.SUTable();

        setPreferredSize(new java.awt.Dimension(0, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(30, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 29));

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSaveChangesForTable.setText("S");
        btnSaveChangesForTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesForTableActionPerformed(evt);
            }
        });

        btnDelete.setText("-");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("X");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveChangesForTable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSaveChangesForTable)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel)))
        );

        jScrollPane4.setBounds(new java.awt.Rectangle(0, 0, 0, 200));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPane4.setViewportView(tblQueryResult);

        tblQueryResult.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblQueryResult.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblQueryResultFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblQueryResultFocusLost(evt);
            }
        });
        tblQueryResult.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblQueryResultPropertyChange(evt);
            }
        });
        tblQueryResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblQueryResultKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(tblQueryResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private SUTable getTable() {
        return (SUTable) tblQueryResult;
    }

    private SUQueryBean query;
    private SUQueryResult result;

    @SneakyThrows
    public void runQuery(SUQueryBean query) {
        this.query = query;

        result = db.runQuery(query);

        SUTable tbl = getTable();
        tbl.refreshData(result);

        tbl.setOnCellChange(cell -> {
            System.out.println("cell="+cell+",cell editing="+cell.isEdited());
            setTableMode(cell.isEdited() ? SU_TABLE_MODE.UPDATE_ENABLE : SU_TABLE_MODE.UPDATE_DISABLE);
        });

        tbl.setOnRowAdd(row -> {
            setTableMode(SU_TABLE_MODE.ADD_ENABLE);
        });

//        tbl.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            
//            public void valueChanged(ListSelectionEvent lse) {
//                if (!lse.getValueIsAdjusting()) {
//                    
//                    ListSelectionModel lsm = (ListSelectionModel) lse.getSource();
//                    int leadIndex = lsm.getLeadSelectionIndex();
//                    int anchIndex = lsm.getAnchorSelectionIndex();
//                    int minIndex = lsm.getMinSelectionIndex();
//                    int maxIndex = lsm.getMaxSelectionIndex();
//                    LogUtil.log("min0 index="+tbl.getSelectionModel().getMinSelectionIndex());
//                    LogUtil.log("min index="+minIndex);
//                    LogUtil.log("max index="+maxIndex);
//                    LogUtil.log("lead index="+leadIndex);
//                    LogUtil.log("anch index="+anchIndex);
////                    saveEditingRow();
//                }
//            }
//        });
    }

    private enum SU_TABLE_MODE {
        UPDATE_ENABLE, UPDATE_DISABLE, ADD_ENABLE, ADD_DISABLE, CANCEL
    }

    private void setTableMode(SU_TABLE_MODE mode) {
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancel.setEnabled(false);
        btnSaveChangesForTable.setEnabled(false);
        if (mode == SU_TABLE_MODE.ADD_ENABLE) {
            btnSaveChangesForTable.setEnabled(true);
            btnCancel.setEnabled(true);
        } else if (mode == SU_TABLE_MODE.ADD_DISABLE) {
            btnAdd.setEnabled(true);
            btnDelete.setEnabled(true);
        } else if (mode == SU_TABLE_MODE.UPDATE_ENABLE) {
            btnSaveChangesForTable.setEnabled(true);
            btnCancel.setEnabled(true);
        } else if (mode == SU_TABLE_MODE.UPDATE_DISABLE) {
            btnAdd.setEnabled(true);
            btnDelete.setEnabled(true);
        } else if (mode == SU_TABLE_MODE.CANCEL) {
            btnAdd.setEnabled(true);
            btnDelete.setEnabled(true);
        }
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        SUTable tbl = getTable();
        SUTableRow addedRow = tbl.addEmptyRow();
        LogUtil.log("row added");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveChangesForTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesForTableActionPerformed
        SUTable tbl = getTable();
        tbl.saveOrInsertRow();
    }//GEN-LAST:event_btnSaveChangesForTableActionPerformed


    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        SUTable tbl = getTable();
        db.deleteRow(query.getConnection(), tbl.getSelectedTableRow());
        runQuery(query);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblQueryResultFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblQueryResultFocusGained
//        SUTable table = getTable();
//        SUTableRow row = table.getSelectedTableRow();
//        LogUtil.log("tblQueryResultFocusGained=" + row);
    }//GEN-LAST:event_tblQueryResultFocusGained

    private void tblQueryResultFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblQueryResultFocusLost
//        SUTable table = getTable();
//        SUTableRow row = table.getSelectedTableRow();
//        LogUtil.log("tblQueryResultFocusLost=" + row);
    }//GEN-LAST:event_tblQueryResultFocusLost

    private void tblQueryResultPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblQueryResultPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblQueryResultPropertyChange

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        SUTable table = getTable();
        table.discardChanges();
       
        setTableMode(SU_TABLE_MODE.CANCEL);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblQueryResultKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblQueryResultKeyTyped
        LogUtil.log("evt.getKeyCode()="+evt.getKeyCode());
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            LogUtil.log("row changed");
        }
    }//GEN-LAST:event_tblQueryResultKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSaveChangesForTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblQueryResult;
    // End of variables declaration//GEN-END:variables
}
